### PR TITLE
deactivate testing with meson

### PR DESCRIPTION
**Pull request by BBasile**

### CODE REVIEW

**Comment by BBasile** [comment]
wow that was so fast green.

**Comment by ximion** [comment]
Have you tried lowering the Python version requirement already, e.g. using `pyenv global system 3.5`?
I am quite puzzled that nobody at Travis considers breaking half of the Python world as an issue - if at least using the system Python version would work, but they make that hard as well.

**Comment by BBasile** [comment]
yes for libdparse i tried a script that made the python version as an environment variable and then use this variable but it didn't worked, which is silly: [see this change](https://github.com/dlang-community/libdparse/pull/330/commits/ee708f0bb2d0a436a0d6f36b1eec155dd1cbcce3).

**Comment by BBasile** [comment]
anyway i just dont care @ximion, if you think you can find a way that doesn't involve installing another python 3 version ([which is super slow](https://travis-ci.org/dlang-community/tinyendian/jobs/466966513#L122)), just do it, even in an experimental PR, just to see. I have nothing against Meson, it's just that for now it sucks a bit to setup it at Travis.

**Pull request closed without merging**
