### PR TITLE
Remove two arguments to the static_library call…

### PR DESCRIPTION
**Pull request by russel**
…that are causing warning with future hard error report.

### CODE REVIEW

**Comment by ximion** [comment]
I think it might be more useful to convert the `static_library` call into just `library`, so we can switch between dynamic and static libraries, and keep the versioning there.

**Comment by BBasile** [comment]
You can fix this if it's required

**Comment by russel** [comment]
@BBasile  @ximion 's proposal would be the other solution, I just went for the minimum solution to removing the warning. If we go with this alternative then I'm happy to provide the pull request that effectively reverts this change and makes the `static_library` → `library` change. Choice of static/shared is then a command line choice. 

I wonder if we could make this project a paradigm of how to build a D library with Meson, and then do D-YAML, DInotify, and Unit-Threaded. I am happy to do the 'leg work' and create the pull requests on the other projects, once we have come to a decision about the best way of doing this so that Debian (and Fedora) packaging is as easy as possible.

**Comment by ximion** [comment]
@russel Initially, when I was still experimenting with packaging D code for Debian, I went with a static library for tinyendian, because it is, well, a tiny package.
The problem with shipping a static library only in Debian and other distros is though that the automatic package rebuild system doesn't catch those, because the static libraries don't depend on the dynamic phobos/druntime libraries. Usually if the druntime/phobos version changes, we rebuild all other packages in order. If the tinyendian package is only provided as static library, it does not get rebuilt, leading to annoying compile failures of packages that depend on it and that are being built with a new GDC/LDC while tinyendian is still on the old version.

This can be fixed by augmenting the `dh-dlang` packaging helper ( https://salsa.debian.org/d-team/dh-dlang ) to just automatically add the appropriate druntime/phobos dependencies depending on the used compiler on rebuild, even if the library is a static build. This is a bit tricky to do correctly, but could be done (needs some Perl scripting).
Or, of course, we just build the shared library instead. That's what I switched the mustache-d package to, because it's a rather simple fix. It also gives users of the Meson build who are not distros the opportunity to decide for themselves whether they want a static or shared library.

**Pull request merged**
